package com.icecream.util;

public enum EAnimType {
	PRESS_X,
	PRESS_BACK,
	PLAYER_RUNNING,
	IDLE_UP,
	IDLE_DOWN,
	IDLE_LEFT,
	IDLE_RIGHT,
	IDLE_HIDE,
	BEER_LEFT,
	BEER_RIGHT,
	BEER_UP,
	BEER_DOWN,
	ENEMY_DRUNK,
	ENEMY_ALERT_LEFT,
	ENEMY_ALERT_RIGHT,
	ENEMY_SHOOT_LEFT,
	ENEMY_SHOOT_RIGHT
}
